name: SpyNPCs
version: 1.0.0
main: com.spygamingog.spynpcs.SpyNPCs
api-version: 1.20
author: SpyGamingOG
depend: [ProtocolLib, SpyCore]
commands:
  spynpc:
    description: Main NPC command
    usage: /spynpc <create|delete|skin|action>
